name: bansi_films_frontend
description: Flutter app with Firebase + FastAPI backend
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (latest)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1

  # Other useful packages
  http: ^1.2.2
  image_picker: ^1.1.2
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
